plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.maven.publish)
}


/**
 * Embeds the vendored specification schemas (`spec/`) in the library as Kotlin source.
 *
 * A catalog's `$ref`s reach into `common_types.json`, so a renderer cannot resolve them without
 * the document. Generating it from the vendored file rather than transcribing it by hand is what
 * keeps the two from drifting: a hand-written copy of a schema is wrong the first time the
 * specification moves and says nothing about it.
 *
 * The text is embedded exactly as vendored, not reformatted, so that what ships can be diffed
 * against the specification's own file.
 */
fun embedSchemas(
    taskName: String,
    packageName: String,
    objectName: String,
    documents: Map<String, String>,
) = tasks.register(taskName) {
    val specDir = layout.projectDirectory.dir("spec")
    val outputDir = layout.buildDirectory.dir("generated/$taskName/kotlin")
    inputs.dir(specDir).withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().asFile.resolve(packageName.replace('.', '/'))
        target.mkdirs()
        val quote = "\""
        val body = documents.entries.joinToString("\n\n") { (name, path) ->
            // Chunked before escaping, not after: splitting the escaped text can cut an escape
            // sequence in half and emit a source file that does not parse.
            val literal = specDir.file(path).asFile.readText().chunked(100).joinToString(
                quote + " +\n            " + quote,
            ) { chunk ->
                chunk.replace("\\", "\\\\")
                    .replace(quote, "\\" + quote)
                    .replace("$", "\\$")
                    .replace("\n", "\\n")
            }
            listOf(
                "    /** `" + path + "`, verbatim. See `spec/README.md` for its provenance. */",
                "    internal const val " + name + ": String =",
                "        " + quote + literal + quote,
            ).joinToString("\n")
        }
        target.resolve("$objectName.kt").writeText(
            listOf(
                "// Generated by the `$taskName` task from `a2ui-core/spec`. Do not edit.",
                "package $packageName",
                "",
                "internal object $objectName {",
                body,
                "}",
                "",
            ).joinToString("\n"),
        )
    }
}

/** The specification documents `a2ui-core` needs at runtime to resolve a catalog's `${'$'}ref`s. */
val generateProtocolSchemas = embedSchemas(
    taskName = "generateProtocolSchemas",
    packageName = "dev.ynagai.a2ui.core.protocol",
    objectName = "ProtocolSchemaSources",
    documents = mapOf(
        "COMMON_TYPES" to "v1_0/common_types.json",
        "AGENT_TO_RENDERER" to "v1_0/agent_to_renderer.json",
    ),
)

/**
 * Catalogs the tests check against.
 *
 * The published basic catalog rather than one written for the occasion: the checker's whole job is
 * to apply what a real catalog says, and a catalog authored alongside the checker would agree with
 * it by construction. Generated into test sources rather than read from disk because the tests run
 * on Kotlin/JS and Kotlin/Wasm in a browser, where there is no disk to read.
 */
val generateCatalogFixtures = embedSchemas(
    taskName = "generateCatalogFixtures",
    packageName = "dev.ynagai.a2ui.core.validation",
    objectName = "CatalogFixtures",
    documents = mapOf("BASIC" to "v1_0/catalogs/basic.json"),
)

kotlin {
    explicitApi()

    @OptIn(org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation::class)
    abiValidation()

    withSourcesJar(publish = true)

    android {
        namespace = "dev.ynagai.a2ui.core"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    jvm()

    iosArm64()
    iosSimulatorArm64()
    macosArm64()

    js { browser() }

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs { browser() }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateProtocolSchemas)
        }
        commonTest {
            kotlin.srcDir(generateCatalogFixtures)
        }
        commonMain.dependencies {
            api(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
